# Site
repository: frankbreetz/frankbreetz.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Frank Breetz
title: Data Engineer
email: frank.breetz@gmail.com
# email_title: Email (Email title override)
phone: 513-518-2946
# phone_title: Phone (Phone title override)
website: breetz.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  frankbreetz
linkedin_username: frank-breetz

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced data engineer with a strong background in designing and implementing data pipelines,performing complex transformations, and managing large-scale projects. Proficient in a variety of programming languages and data tools, including Python, SQL, Apache Airflow, Apache NiFi, and AWS.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Astronomer
        sub_title: Data Engineer
        caption: Jul 2021 - Apr 2023
        link: https://www.astronomer.io/
        quote: >
           Astronomer is the commercial developer of Apache Airflow, a community-driven open-source tool that's leading the market in data orchestration. We're a globally-distributed and rapidly growing venture-backed team of learners, innovators and collaborators.
        description: | # this will include new lines to allow paragraphs
           - Performed in-depth data analysis, quickly identifying and resolving complex issues using Apache Airflow, Python, SQL, Docker, Kubernetes, and a variety of other tools.
           - Conducted architecture reviews on multiple customer cloud environments on AWS, GCP, and Azure. 
           - Developed custom Flask-based migration tools that reduced migration time by over 70%, while improving data quality by over 50%.

      - layout: right
        title: Linquest
        sub_title: Data Architect
        caption: Aug 2018 - Jul 2021
        link: https://www.linquest.com/
        quote: >
          LinQuest is a national security space leader that enables defense and intelligence missions through advanced digital solutions and the development, integration, and operation of mission critical systems.
        description: | # this will include new lines to allow paragraphs
          - Designed and developed scalable data models for PostgreSQL using Erwin.
          - Led the end-to-end design and implementation of data pipelines from scratch, integrating Python,PostgreSQL, and MongoDB.
          - Orchestrated complex data workflows using Apache Airflow on AWS and HDFS clusters, ensuring timely delivery of high-quality datasets to downstream systems.
      - layout: right
        title: SigmaTEK
        sub_title: Project Manager/Software Developer
        caption: Jan 2014 - Aug 2018
        link: https://www.sigmanest.com/
        quote: >
          SigmaTEK offers a variety of software products and business solutions developed by our expert team of engineers. From quoting and nesting to total shop floor automation, SigmaTEK offers a complete solution for every aspect of the manufacturing process.
        description: | # this will include new lines to allow paragraphs
          - Managed up to 5 simultaneous projects, ranging from $200K-$500K, while consistently meeting or exceeding project timelines and budgets.
          - Reduced software defects by 50% through effective management of feature requests and prioritization of bug fixes based on customer impact.
          - Developed and integrated custom applications for 10+ clients, resulting in a 95% satisfaction rate and increased revenue.
  - title: Education
    layout: list
    content:
      - layout: center
        title: Georgia Institute of Technology
        sub_title: Master of Science in Computer Science
        caption: 2018-2020
      - layout: center
        title: Northern Kentucky University
        sub_title: Bachelor of Science in Physics (Manga Cum Laude)
        caption: 2010-2013
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming: Python, SQL
      - ETL/ELT: Airflow, Kafka
      - Cloud Platforms: AWS, GCP
      - Big Data: Hadoop, NiFi
      - Data Warehousing
      - Data Governance
      - Data Modeling: Erwin
      - NoSQL Databases: MongoDB
      - Version Control: git
      - Containerization: Docker, Kubernetes
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
